version: "3"
services:
  personnel:
    environment:
      TZ: Europe/Oslo
      fint.adapter.organizations: fintlabs.no
      fint.adapter.endpoints.providers.personal: https://beta.felleskomponent.no/administrasjon/personal/provider
      fint.adapter.endpoints.providers.organisasjon: https://beta.felleskomponent.no/administrasjon/organisasjon/provider
      fint.adapter.endpoints.providers.kodeverk: https://beta.felleskomponent.no/administrasjon/kodeverk/provider
      fint.oauth.enabled: "true"
      fint.oauth.access-token-uri: https://idp.felleskomponent.no/nidp/oauth/nam/token
      fint.oauth.scope: fint-client
    image: dtr.fintlabs.no/beta/fint-springer-adapter
    deploy:
      placement:
        constraints:
        - node.role == worker
        - node.labels.com.docker.ucp.collection == shared
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  student:
    environment:
      TZ: Europe/Oslo
      fint.oauth.scope: fint-client
    image: dtr.fintlabs.no/beta/fake-student-adapter
    deploy:
      placement:
        constraints:
        - node.role == worker
        - node.labels.com.docker.ucp.collection == shared
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
