version: "3.1"
secrets:
  fint-mongo:
    external: true
services:
  springer:
    environment:
      TZ: Europe/Oslo
      fint.adapter.organizations: fintlabs.no
      fint.adapter.endpoints.providers.personal: https://beta.felleskomponent.no/administrasjon/personal/provider
      fint.adapter.endpoints.providers.organisasjon: https://beta.felleskomponent.no/administrasjon/organisasjon/provider
      fint.adapter.endpoints.providers.kodeverk: https://beta.felleskomponent.no/administrasjon/kodeverk/provider
      fint.adapter.endpoints.providers.elev: https://beta.felleskomponent.no/utdanning/elev/provider
      fint.oauth.enabled: "true"
      fint.oauth.access-token-uri: https://idp.felleskomponent.no/nidp/oauth/nam/token
      fint.oauth.scope: fint-client
      spring.data.mongodb.database: springer
    image: dtr.fintlabs.no/beta/fint-springer-adapter:latest
    secrets:
    - source: fint-mongo
      target: spring.data.mongodb.uri
