apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\noasgnil\go\bin\kompose.exe convert -d -f .\docker-stack.yml
    kompose.version: 1.16.0 (HEAD)
  labels:
    io.kompose.service: springer-adapter
  name: springer
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      io.kompose.service: springer-adapter
  template:
    metadata:
      labels:
        io.kompose.service: springer-adapter
    spec:
      containers:
      - name: springer-adapter
        image: fintlabs.azurecr.io/fint-springer-adapter
        env:
        - name: TZ
          value: Europe/Oslo
        - name: fint.adapter.endpoints.providers.elev
          value: https://beta.felleskomponent.no/utdanning/elev/provider
        - name: fint.adapter.endpoints.providers.kodeverk
          value: https://beta.felleskomponent.no/administrasjon/kodeverk/provider
        - name: fint.adapter.endpoints.providers.organisasjon
          value: https://beta.felleskomponent.no/administrasjon/organisasjon/provider
        - name: fint.adapter.endpoints.providers.personal
          value: https://beta.felleskomponent.no/administrasjon/personal/provider
        - name: fint.adapter.endpoints.providers.timeplan
          value: https://beta.felleskomponent.no/utdanning/timeplan/provider
        - name: fint.adapter.organizations
          value: fintlabs.no
        - name: fint.oauth.access-token-uri
          value: https://idp.felleskomponent.no/nidp/oauth/nam/token
        - name: fint.oauth.client-id
          valueFrom:
            secretKeyRef:
              name: fake-adapter
              key: client-id
        - name: fint.oauth.client-secret
          valueFrom:
            secretKeyRef:
              name: fake-adapter
              key: client-secret
        - name: fint.oauth.enabled
          value: "true"
        - name: fint.oauth.password
          valueFrom:
            secretKeyRef:
              name: fake-adapter
              key: password
        - name: fint.oauth.scope
          value: fint-client
        - name: fint.oauth.username
          valueFrom:
            secretKeyRef:
              name: fake-adapter
              key: username
        - name: spring.data.mongodb.uri
          valueFrom:
            secretKeyRef:
              name: fint-mongo
              key: mongodb
        - name: spring.data.mongodb.database
          value: springer
      restartPolicy: Always
