server:
  port: 8091

fint:
  springer:
    reseedTypes:
      - no.novari.fint.model.resource.felles.PersonResource
      - no.novari.fint.model.resource.administrasjon.personal.PersonalressursResource
      - no.novari.fint.model.resource.utdanning.utdanningsprogram.ArstrinnResource
      - no.novari.fint.model.resource.utdanning.elev.KlasseResource
      - no.novari.fint.model.resource.utdanning.elev.ElevforholdResource
      - no.novari.fint.model.resource.utdanning.elev.SkoleressursResource
      - no.novari.fint.model.resource.utdanning.timeplan.UndervisningsgruppeResource
      - no.novari.fint.model.resource.utdanning.timeplan.UndervisningsgruppemedlemskapResource

  adapter:
    endpoints:
      sse: /sse/%s
      status: /status
      response: /response
    organizations: fintlabs.no

  oauth:
    enabled: false
    access-token-uri: https://idp.felleskomponent.no/nidp/oauth/nam/token
    scope: fint-client
