security:
 basic:
  enabled: false

fint:
 adapter:
  organizations: fintlabs.no
  sse-endpoint: http://localhost:8081/provider/sse/%s
  status-endpoint: http://localhost:8081/provider/status
  response-endpoint: http://localhost:8081/provider/response

 oauth:
  enabled: false
