security:
  basic:
    enabled: false

fint:
  adapter:
    organizations: mock.no
    endpoints:
      providers:
        personal: http://localhost:8081/provider

  oauth:
    enabled: false

logging:
  level:
    no.fint.provider: TRACE
