name: Build, Push and Deploy

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: write
  contents: read

jobs:

  build-push:
    uses: fintlabs/shared-workflows/.github/workflows/java-gradle-build-push.yaml@v0
    with:
      java-version: '21'
    secrets: inherit

  pwf:
    needs: build-push
    uses: fintlabs/shared-workflows/.github/workflows/kustomize-deploy.yaml@v0
    with:
      tags: ${{ needs.build-push.outputs.tags }}
      environment: pwf
      deploy-every-branch: true
    secrets: inherit